name: zic
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  http: ^1.6.0
  shared_preferences: ^2.5.4
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  spinning_wheel: ^0.0.7
  flutter_fortune_wheel: ^1.3.2

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/3d.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  
  # For Android 12+
  android_12:
    color: "#FFFFFF"
    image: "assets/images/3d.png"
    
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"


  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"
  
  remove_alpha_ios: true



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
